name: ğŸ“ Checklist Validator
run-name: ğŸ“ Checklist Validator for issue ${{ github.event.issue.number }}

on:
  issues:
    types:
      - closed

jobs:
  checklist-validation:
    name: âœ… Checklist Completion Check
    runs-on: ubuntu-22.04
    steps:
      - uses: manticoresoftware/manticoresearch/actions/checklist-validator@master
    