name: ðŸªž Mirror
run-name: ðŸªž Mirror ${{ github.sha }}

on:
  push:
    branches:
      - master
      - maintenance-release
      - 'manticore-*'

# waits until the previous workflow run to finish when a new one appears
concurrency:
  group: mirror_${{ github.ref }}

jobs:
  to_gitlab:
    name: Sync to GitLab
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Sync to Gitlab
        run: |
          echo "${{ secrets.GITLAB_SSH_KEY }}" > /tmp/ssh.key
          chmod 600 /tmp/ssh.key
          git remote add gitlab git@gitlab.com:manticoresearch/dev.git
          git checkout ${{ github.ref }}
          GIT_SSH_COMMAND='ssh -i /tmp/ssh.key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -F /dev/null' git fetch gitlab
          GIT_SSH_COMMAND='ssh -i /tmp/ssh.key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -F /dev/null' git push -u gitlab ${{ github.ref }}
        shell: bash
